# permissions for end users to edit loginsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: loginset-editor-role
rules:
- apiGroups:
  - slinky.slurm.net
  resources:
  - loginsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - loginsets/status
  verbs:
  - get
